/* Generated by cbindgen - do not edit */

#ifndef KOAN_AUDIO_FFI_H
#define KOAN_AUDIO_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Ping function to verify C FFI is working.
 */
int koan_ping(void);

#endif  /* KOAN_AUDIO_FFI_H */
